# Generated by Django 5.0.6 on 2024-05-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(db_index=True, max_length=150, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Name'),
        ),
    ]
